### PR TITLE
Fixture for issue #14 - jsdoc() wrong handling of optional parameters…

### PR DESCRIPTION
**Pull request by mwittig**
…. Added test case.

Fixed typo in README
Updated to dependency "ink-docstrap" to current release

### CODE REVIEW

**Comment by mwittig** [comment]
Finally, builds are passing and coverage has also increaed compared to previous builds :)

**Comment by mlucool** [comment]
Looks good, but please squash

**Comment by mwittig** [comment]
Done

**Comment by mlucool** [comment]
:+1: thanks!

**Pull request merged**
