### PR TITLE
Drop dependency on deprecated `gulp-util`

### PR DESCRIPTION
**Pull request by anwarhahjjeffersongeorge**
Replaces
- gulp-util.log() with fancy-log.log(),
- gulp-util.beep with beeper(),  and
- gulp-utiil.log(gulp-util.colors.red()) with fancy-log.error()

See https://github.com/gulpjs/gulp/issues/2065

### CODE REVIEW

**Comment by mlucool** [comment]
Thanks for your contribution!

**Comment by paulsmirnov** [comment]
Note that `fancy-log.error()` writes to `stderr` instead of `stdout`, it could corrupt the log like it did in my project.

**Comment by FizzyGalacticus** [comment]
Can we expect this to be pushed to npm anytime soon?

**Comment by mlucool** [comment]
I'll publish in the next week. I was hoping to avoid publishing without any new features to offer then forgot about this change

**Comment by mlucool** [comment]
Published with more upgrades and dropping support for unsupported versions of node

**Pull request merged**
