### PR TITLE
Cloning config

### PR DESCRIPTION
**Pull request by kevincolten**
resolves https://github.com/mlucool/gulp-jsdoc3/issues/36

### CODE REVIEW

**Comment by mlucool** [comment]
Thanks for the PR, can you add a test for the type of things this fixed?

**Comment by kevincolten** [comment]
@mlucool Test added!

**Comment by mlucool** [comment]
Thanks for the fix @kevincolten

**Comment by kevincolten** [comment]
@mlucool When do you plan on publishing the latest release to npmjs.org?

**Comment by minkyu-yi** [comment]
@kevincolten  👍 
@mlucool  when it will be released?

**Comment by mlucool** [comment]
Hopefully this week. Sorry for the delay.

**Pull request merged**
